name       : iscan
version    : 2.30.3
release    : 4
source     :
    - http://support.epson.net/linux/src/scanner/iscan/iscan_2.30.3-1.tar.gz : 91a6cc1571e5ec34cee067eabb35f13838e71dfeda416310ecb5b5030d49de67
license    : GPL-2.0
component  : desktop.core
summary    : Image Scan! is a graphical scanner utility
description: |
    Image Scan! is a graphical scanner utility
builddeps  :
    - pkgconfig(gimp-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(sane-backends)
rundeps    :
    - iscan-data
setup      : |
    %patch -p0 < $pkgfiles/libpng15.patch
    %patch -p0 < $pkgfiles/jpegstream.patch
    ln -s libesmod-x86_64.c2.so non-free/libesmod-x86_64.so
    %configure --enable-frontend
build      : |
    %make -j1
install    : |
    %make_install
    # Register the device with sane
    install -d -m 00755 $installdir/etc/sane.d/dll.d
    install -d -m 00755 $installdir/usr/share/applications
    install -D -m 00644 backend/epkowa.conf $installdir/etc/sane.d/epkowa.conf
    install -D -m 00644 iscan.desktop $installdir/usr/share/applications/iscan.desktop
    echo "epkowa" > $installdir/etc/sane.d/dll.d/epkowa.conf
