name       : iscan
version    : 2.30.4
release    : 5
source     :
    - http://support.epson.net/linux/src/scanner/iscan/iscan_2.30.4-2.tar.gz : 597b9913de42d7a27f95bc82e533cbe778121ba13e3a03bc037f8d09a43447d5
license    : GPL-2.0-or-later
component  : desktop.core
summary    : Image Scan! is a graphical scanner utility for EPSON scanners.
description: |
    Image Scan! is a graphical scanner utility for EPSON scanners.
builddeps  :
    - pkgconfig(gimp-2.0)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(sane-backends)
rundeps    :
    - iscan-data
setup      : |
    %patch -p0 < $pkgfiles/libpng15.patch
    %patch -p0 < $pkgfiles/jpegstream.patch
    ln -s libesmod-x86_64.c2.so non-free/libesmod-x86_64.so
    %configure --enable-frontend
build      : |
    %make -j1
install    : |
    %make_install
    # Register the device with sane
    install -dm00755 $installdir/etc/sane.d/dll.d
    install -dm00644 $installdir/usr/share/applications
    install -Dm00644 backend/epkowa.conf $installdir/etc/sane.d/epkowa.conf
    install -Dm00644 iscan.desktop $installdir/usr/share/applications/iscan.desktop
    echo "epkowa" > $installdir/etc/sane.d/dll.d/epkowa.conf
